# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9890d54b6f3b2d24c8ac8759d552b217f4d404dff7692adce4ff0332a7d011ddda790c0db47e997d1f05d93562e706c8afe877492acb2dc0f8f8aa1416d9e468

test:
  secret_key_base: be71d513bcaa693c08c1b737b9bc4fe13b8b18b9edf7584098a5529d4cc1233ff9d9256ed760ed7d4458e5fabf1f41ecdc349997cb9d06703311c7b2ff49a67a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
